# ===================================================================
# Archivo: toolkit.conf
# Responsabilidad: Almacenar variables globales.
# ===================================================================

export TK_VERSION="1.0.0"

export TK_MODULES_DIR="${TK_BASE_DIR}/modules"
export TK_LOGS_DIR="${TK_BASE_DIR}/logs"
export TK_TMP_DIR="${TK_BASE_DIR}/tmp"
export TK_REPORTS_DIR="${TK_BASE_DIR}/reports"

export TK_LOG_LEVEL="INFO"
export TK_LOG_FILE="${TK_LOGS_DIR}/toolkit_system.log"
